//! Build script that materialises per-vector `#[test]` functions for the
//! upstream conformance suite.
//!
//! When the `upstream-conformance` cargo feature is enabled, walks each of
//! the seven fixture areas under `tests/conformance/upstream/fixtures/` and
//! emits one test function per leaf vector:
//!
//!   * `ouroboros-consensus/`  → one test per CBOR golden file
//!   * `cardano-ledger/`       → one test per `.cddl` / `.json` / `.cbor` file
//!   * `cardano-node/`         → one test per `.json` genesis-spec / golden file
//!   * `cardano-base/`         → one test per `vrf*.txt` vector file
//!   * `mithril/`              → one test per `.json` certificate fixture
//!   * `ledger-rules/`         → one test per `<RULE>/test_N/` directory
//!     (5,603 vectors at the v20260524 corpus tag)
//!
//! The runtime harness lives in `tests/upstream_tests.rs`; this script only
//! generates the entries it `include!`s.
//!
//! ## Corpus location
//!
//! Searched in order:
//!   1. `$DUGITE_UPSTREAM_FIXTURES_DIR/<area>/` — explicit override.
//!   2. `<crate_root>/upstream/fixtures/<area>/` — populated by
//!      `cargo xtask download-upstream-fixtures [--area <area>]`.
//!
//! When the feature is off, or the corpus is missing, emits an empty file
//! so the `include!` still compiles and the umbrella tests in
//! `upstream_tests.rs` (the `*_golden_decodes` / `*_checks` family) remain
//! the visible coverage signal.

use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let crate_root = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let out_file = out_dir.join("generated_upstream_tests.rs");

    let enabled = env::var_os("CARGO_FEATURE_UPSTREAM_CONFORMANCE").is_some();
    if !enabled {
        fs::write(&out_file, "// upstream-conformance feature disabled\n")
            .expect("write empty generated_upstream_tests.rs");
        return;
    }

    let fixtures_root = if let Ok(dir) = env::var("DUGITE_UPSTREAM_FIXTURES_DIR") {
        PathBuf::from(dir)
    } else {
        crate_root.join("upstream").join("fixtures")
    };

    println!("cargo:rerun-if-changed={}", fixtures_root.display());
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=DUGITE_UPSTREAM_FIXTURES_DIR");

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by tests/conformance/build.rs — do not edit.\n");
    out.push_str("// One #[test] per upstream-fixture vector across all 6 areas.\n\n");

    let mut total = 0usize;
    let mut used_names: BTreeSet<String> = BTreeSet::new();

    // ── file-based areas ────────────────────────────────────────────
    for (area, kind) in [
        ("ouroboros_consensus", "ouroboros-consensus"),
        ("cardano_ledger", "cardano-ledger"),
        ("cardano_node", "cardano-node"),
        ("cardano_base", "cardano-base"),
        ("mithril", "mithril"),
    ] {
        let dir = fixtures_root.join(kind);
        if !dir.is_dir() {
            continue;
        }
        let mut files = collect_files(&dir);
        files.sort();
        for path in &files {
            // Skip stub README sentinels — they aren't real vectors.
            if path
                .file_name()
                .and_then(|n| n.to_str())
                .map(|n| n.eq_ignore_ascii_case("readme.txt"))
                .unwrap_or(false)
            {
                continue;
            }
            let rel = path.strip_prefix(&dir).unwrap_or(path);
            let rel_str = rel
                .to_string_lossy()
                .replace(std::path::MAIN_SEPARATOR, "/");
            let name = unique_name(
                &mut used_names,
                &format!("upstream_{area}_{}", sanitise(&rel_str)),
            );
            let abs = path.display().to_string();
            out.push_str(&format!(
                "#[test]\nfn {name}() {{\n    \
                 let path = std::path::Path::new({abs:?});\n    \
                 if let Err(reason) = dugite_conformance::upstream::{area}::check_one_file(path) {{\n        \
                 panic!(\"{rel_str}: {{reason}}\");\n    \
                 }}\n}}\n\n",
            ));
            total += 1;
        }
    }

    // ── ledger-rules: per `<RULE>/test_N/` directory ────────────────
    let lr_dir = fixtures_root.join("ledger-rules");
    if lr_dir.is_dir() {
        let mut test_dirs = collect_ledger_rules_test_dirs(&lr_dir);
        test_dirs.sort();
        for test_dir in &test_dirs {
            let rel = test_dir.strip_prefix(&lr_dir).unwrap_or(test_dir);
            let rel_str = rel
                .to_string_lossy()
                .replace(std::path::MAIN_SEPARATOR, "/");
            let name = unique_name(
                &mut used_names,
                &format!("upstream_ledger_rules_{}", sanitise(&rel_str)),
            );
            let abs = test_dir.display().to_string();
            out.push_str(&format!(
                "#[test]\nfn {name}() {{\n    \
                 use dugite_conformance::upstream::ledger_rules_replay::{{check_one_test_dir, VectorOutcome}};\n    \
                 let path = std::path::Path::new({abs:?});\n    \
                 match check_one_test_dir(path) {{\n        \
                 VectorOutcome::Pass => {{}}\n        \
                 VectorOutcome::Skip(reason) => eprintln!(\"SKIP {rel_str}: {{reason}}\"),\n        \
                 VectorOutcome::Fail(reason) => panic!(\"{rel_str}: {{reason}}\"),\n    \
                 }}\n}}\n\n",
            ));
            total += 1;
        }
    }

    if total == 0 {
        out.push_str(
            "// No fixtures discovered. Populate via `cargo xtask download-upstream-fixtures`.\n",
        );
    } else {
        out.push_str(&format!("// {total} per-vector test(s) generated.\n"));
    }

    fs::write(&out_file, out).expect("write generated_upstream_tests.rs");
}

/// Recursively collect every regular file under `dir`.
fn collect_files(dir: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    fn walk(dir: &Path, acc: &mut Vec<PathBuf>) {
        let Ok(rd) = fs::read_dir(dir) else {
            return;
        };
        for entry in rd.flatten() {
            let p = entry.path();
            if p.is_file() {
                acc.push(p);
            } else if p.is_dir() {
                walk(&p, acc);
            }
        }
    }
    walk(dir, &mut out);
    out
}

/// A `ledger-rules` test directory is a leaf `test_N` directory containing
/// the canonical `conformance_dump_*` CBOR files.
fn collect_ledger_rules_test_dirs(root: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let Ok(rd) = fs::read_dir(root) else {
        return out;
    };
    for entry in rd.flatten() {
        let rule_dir = entry.path();
        if !rule_dir.is_dir() {
            continue;
        }
        let Ok(rule_rd) = fs::read_dir(&rule_dir) else {
            continue;
        };
        for sub in rule_rd.flatten() {
            let p = sub.path();
            // A test_N directory is identified by the presence of the
            // canonical `conformance_dump_st.cbor` file.
            if p.is_dir() && p.join("conformance_dump_st.cbor").is_file() {
                out.push(p);
            }
        }
    }
    out
}

/// Convert an arbitrary string into a valid Rust identifier (snake_case,
/// `[a-z0-9_]+`).
fn sanitise(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut prev_underscore = false;
    for ch in s.chars() {
        let mapped = if ch.is_ascii_alphanumeric() {
            ch.to_ascii_lowercase()
        } else {
            '_'
        };
        if mapped == '_' {
            if !prev_underscore && !out.is_empty() {
                out.push('_');
                prev_underscore = true;
            }
        } else {
            out.push(mapped);
            prev_underscore = false;
        }
    }
    // Trim trailing underscore, ensure non-empty + starts with a letter.
    while out.ends_with('_') {
        out.pop();
    }
    if out.is_empty() {
        out.push('v');
    }
    if out
        .chars()
        .next()
        .map(|c| c.is_ascii_digit())
        .unwrap_or(false)
    {
        out.insert(0, 'v');
    }
    out
}

/// Ensure the generated test name is unique within the binary (the
/// sanitise collapse can produce duplicates across e.g. `Block_Conway`
/// in different N2N-version dirs once trailing version digits collapse).
fn unique_name(used: &mut BTreeSet<String>, base: &str) -> String {
    if used.insert(base.to_string()) {
        return base.to_string();
    }
    for n in 2.. {
        let candidate = format!("{base}_{n}");
        if used.insert(candidate.clone()) {
            return candidate;
        }
    }
    unreachable!("name uniquification ran out of integers")
}
