#!/usr/bin/env bash
# Materialise the Plutus binaries the zoo needs, from UPSTREAM artifacts.
#
# WHAT CHANGED AND WHY (#969 / #970)
# ----------------------------------
# This script used to shell out to `aiken` to compile always-true / always-false
# V3 validators, and to write two hand-vendored V1/V2 always-true blobs.
#
# Two problems with that.
#
# 1. An always-true validator NEVER READS THE SCRIPT CONTEXT. So the devnet
#    proved dugite builds a context, resolves the right redeemer pointer,
#    charges a budget and reaches cardano-node's accept/reject verdict — but
#    never that the context's CONTENTS are correct. A wrong field, a wrong list
#    order or a missing entry passed every Plutus test in the gate. #772 was
#    exactly that bug class.
#
# 2. Aiken is a third-party compiler, so using it as the reference is circular:
#    if its stdlib's view of the ScriptContext and dugite's construction share a
#    misunderstanding, the validator agrees with the bug and passes. #772
#    already recorded that — "aiken parity is circular".
#
# Both are fixed by using IntersectMBO's own artifacts.
# `Test.Cardano.Ledger.Plutus.Examples` in cardano-ledger is generated by
# `plutus-preprocessor` from plutus-tx source using `plutus-tx-plugin`, and the
# COMPILED BYTES ARE CHECKED IN. They are vendored into this repo at
# `tests/conformance/upstream/plutus-examples.json` (regenerate with
# `scripts/regenerate-conformance-corpus/extract-plutus-examples.py`), and
# `crates/dugite-uplc/tests/upstream_plutus_examples.rs` pins that dugite
# reproduces upstream's own ScriptHash for all 55 of them.
#
# Net effect: NO GHC, NO aiken, no network access at devnet setup time, and the
# validators actually inspect the thing under test.
#
# SEMANTICS — these are NOT drop-in "always true"
# ----------------------------------------------
# Upstream's scripts assert on the purpose and on datum presence, which is the
# point. Pick the right one for the call site:
#
#   alwaysSucceedsNoDatum    succeeds for every purpose EXCEPT a spending
#                            script that carries a datum. V1/V2 take
#                            (redeemer, context) and FAIL on Spending outright,
#                            because a V1/V2 spending script must have a datum.
#   alwaysSucceedsWithDatum  succeeds ONLY for a spending script with a datum.
#   alwaysFailsNoDatum       the exact inverse of alwaysSucceedsNoDatum: true
#                            only for spending-with-datum, so it fails
#                            everywhere the zoo uses it as "always false".
#   purposeIsWellformed*     the context-inspecting ones — they check that the
#                            ScriptInfo's subject actually appears in the
#                            corresponding TxInfo field (mint value, inputs,
#                            withdrawals, certificates, votes).
#
# Output: $ZOO_LIB/plutus/upstream-<script-name>-<lang>.plutus, plus the legacy
# names the existing zoo scripts reference, aliased to the correct upstream
# script for each one's purpose (see ALIASES below).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$SCRIPT_DIR/tx-zoo-common.sh"

PLUTUS_DIR="$ZOO_LIB/plutus"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"
FIXTURE="$REPO_ROOT/tests/conformance/upstream/plutus-examples.json"

# Legacy file name -> "<upstreamScriptName>|<lang>".
#
# The legacy names are kept so the zoo scripts that reference them do not all
# have to change at once, but the mapping is spelled out here rather than
# hidden, because it is NOT a rename — the right choice differs per call site:
#
#   always-true-v1/v2       used ONLY by spending tests (03a, 03b, 03g, 03h,
#                           03k, 03l, 03m, 08d), which necessarily carry a
#                           datum in V1/V2  => alwaysSucceedsWithDatum
#   always-true-v1/v2-mint  the minting counterparts (03d, 03e), no datum
#                                            => alwaysSucceedsNoDatum
#   always-true-v3          03f (mint) and all of 13-script-purposes (certify,
#                           reward, vote, propose): alwaysSucceedsNoDatum
#                           succeeds for every one of those
#   always-true-v3-spend    03c. EVERY spending test in the zoo carries a datum
#                           — 03c uses an inline one — so the spend cases need
#                           WithDatum even in V3, where the datum is optional.
#                           Getting this wrong is not subtle: the V3 NoDatum
#                           script fails outright with `PT5` at build time.
#   always-false-v3         13f wants a guaranteed failure on CERTIFYING, and
#                           alwaysFailsNoDatum is false there
#   always-false-v3-spend   03j wants a guaranteed failure on SPENDING, and
#                           alwaysFailsNoDatum returns TRUE for
#                           spending-with-datum — the inverse. alwaysFailsWithDatum
#                           is the false-for-spending one
ALIASES=(
    "always-true-v1.plutus|alwaysSucceedsWithDatum|V1"
    "always-true-v2.plutus|alwaysSucceedsWithDatum|V2"
    "always-true-v1-mint.plutus|alwaysSucceedsNoDatum|V1"
    "always-true-v2-mint.plutus|alwaysSucceedsNoDatum|V2"
    "always-true-v3.plutus|alwaysSucceedsNoDatum|V3"
    "always-true-v3-spend.plutus|alwaysSucceedsWithDatum|V3"
    "always-false-v3.plutus|alwaysFailsNoDatum|V3"
    "always-false-v3-spend.plutus|alwaysFailsWithDatum|V3"
)

# Bump when the mapping above changes. The cache is keyed on this AND the
# fixture's cardano-ledger ref.
#
# The old cache check was "cborHex looks long enough", which happily reused a
# binary built from a DIFFERENT handler set: a script missing the
# publish/vote/propose handlers still had a plausible length, so every
# Certifying/Voting/Proposing test failed looking exactly like a dugite bug
# (#955). Key the cache on the actual inputs instead.
PLUTUS_SET_VERSION=upstream-2

_envelope_type() {
    case "$1" in
        V1) echo "PlutusScriptV1" ;;
        V2) echo "PlutusScriptV2" ;;
        V3) echo "PlutusScriptV3" ;;
        V4) echo "PlutusScriptV4" ;;
        *) return 1 ;;
    esac
}

_kebab() {
    printf '%s' "$1" | sed -E 's/([a-z0-9])([A-Z])/\1-\2/g' | tr '[:upper:]' '[:lower:]'
}

_envelope_file() {
    printf '%s/upstream-%s-%s.plutus' \
        "$PLUTUS_DIR" "$(_kebab "$1")" "$(printf '%s' "$2" | tr '[:upper:]' '[:lower:]')"
}

# cardano-cli's textEnvelope `cborHex` is the script bytes wrapped in ONE more
# CBOR byte string than `serialiseCompiledCode` produces. Feeding it the
# single-wrapped form is what used to fail script load with "TooMuchSpace".
_wrap_cbor_bytes() {
    python3 - "$1" <<'PY'
import sys
b = bytes.fromhex(sys.argv[1])
n = len(b)
if n < 24:
    hdr = bytes([0x40 + n])
elif n < 256:
    hdr = bytes([0x58, n])
elif n < 65536:
    hdr = bytes([0x59, (n >> 8) & 0xff, n & 0xff])
else:
    hdr = bytes([0x5a]) + n.to_bytes(4, "big")
sys.stdout.write((hdr + b).hex())
PY
}

# Write every vendored upstream script as a cardano-cli text envelope.
write_upstream_plutus() {
    if [ ! -s "$FIXTURE" ]; then
        zoo_fail "missing $FIXTURE — regenerate with scripts/regenerate-conformance-corpus/extract-plutus-examples.py"
        return 1
    fi
    command -v python3 >/dev/null || { zoo_fail "python3 required to build plutus envelopes"; return 1; }

    local ref; ref="$(jq -r '.source_ref' "$FIXTURE")"
    local written=0 name lang hexs type_ file wrapped

    while IFS='|' read -r name lang hexs; do
        [ -n "$name" ] || continue
        type_="$(_envelope_type "$lang")" || continue
        file="$(_envelope_file "$name" "$lang")"
        wrapped="$(_wrap_cbor_bytes "$hexs")"
        jq -n --arg t "$type_" \
              --arg d "$name ($lang) — plutus-tx via cardano-ledger $ref" \
              --arg c "$wrapped" \
              '{type:$t, description:$d, cborHex:$c}' > "$file"
        written=$((written + 1))
    done < <(jq -r '.scripts[] | .name as $n | .languages | to_entries[] | "\($n)|\(.key)|\(.value.script_hex)"' "$FIXTURE")

    if [ "$written" -lt 40 ]; then
        zoo_fail "only wrote $written plutus envelopes — the fixture looks truncated"
        return 1
    fi
    zoo_ok "wrote $written upstream plutus envelopes (cardano-ledger $ref) to $PLUTUS_DIR"

    local spec alias_file src_name src_lang src_file
    for spec in "${ALIASES[@]}"; do
        alias_file="${spec%%|*}"
        src_name="$(printf '%s' "$spec" | cut -d'|' -f2)"
        src_lang="$(printf '%s' "$spec" | cut -d'|' -f3)"
        src_file="$(_envelope_file "$src_name" "$src_lang")"
        if [ ! -s "$src_file" ]; then
            zoo_fail "alias $alias_file wants $src_file which was not written"
            return 1
        fi
        cp "$src_file" "$PLUTUS_DIR/$alias_file"
    done
    zoo_ok "aliased ${#ALIASES[@]} legacy plutus names"
    return 0
}

# Assert each generated envelope hashes to the value UPSTREAM recorded.
#
# Not belt-and-braces: this is what makes the envelope wrapping above
# trustworthy. A wrapping bug produces a file cardano-cli still loads, under a
# DIFFERENT script hash — so every script address in the zoo would move and the
# resulting failures would look like ledger bugs.
verify_upstream_hashes() {
    command -v cardano-cli >/dev/null || { zoo_info "cardano-cli absent — skipping hash verification"; return 0; }
    local bad=0 checked=0 skipped=0 name lang want file got
    while IFS='|' read -r name lang want; do
        [ -n "$name" ] || continue
        _envelope_type "$lang" >/dev/null 2>&1 || continue
        file="$(_envelope_file "$name" "$lang")"
        [ -s "$file" ] || continue
        got="$(cardano-cli hash script --script-file "$file" 2>/dev/null || true)"
        if [ -z "$got" ]; then
            # cardano-cli 11 does not know PlutusScriptV4; count it rather than
            # letting it vanish into an implied full-coverage number.
            skipped=$((skipped + 1))
            continue
        fi
        checked=$((checked + 1))
        if [ "$got" != "$want" ]; then
            zoo_fail "hash mismatch $name/$lang: envelope=$got upstream=$want"
            bad=$((bad + 1))
        fi
    done < <(jq -r '.scripts[] | .name as $n | .languages | to_entries[] | "\($n)|\(.key)|\(.value.script_hash)"' "$FIXTURE")

    if [ "$bad" -gt 0 ]; then
        zoo_fail "$bad of $checked plutus envelopes hash differently from cardano-ledger"
        return 1
    fi
    if [ "$checked" -lt 39 ]; then
        zoo_fail "only $checked envelope hashes verified (expected >= 39 for V1-V3) — \
this check measured almost nothing"
        return 1
    fi
    zoo_ok "verified $checked plutus envelope hashes against cardano-ledger ($skipped unsupported by this cardano-cli)"
    return 0
}

build_plutus_all() {
    mkdir -p "$PLUTUS_DIR"
    local marker="$PLUTUS_DIR/.plutus-set"
    local ref; ref="$(jq -r '.source_ref' "$FIXTURE" 2>/dev/null || echo unknown)"
    local want="$PLUTUS_SET_VERSION@$ref"

    if [ -f "$marker" ] && [ "$(cat "$marker" 2>/dev/null)" = "$want" ] \
       && [ -s "$PLUTUS_DIR/always-true-v3.plutus" ]; then
        zoo_info "plutus binaries already current ($want) — skipping"
        return 0
    fi

    write_upstream_plutus || return 1
    verify_upstream_hashes || return 1
    echo "$want" > "$marker"
}

# Allow direct execution.
if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    build_plutus_all
fi
