#!/usr/bin/env bash
# Capture step for the ledger-rules area.
#
# ## Approach: patched ImpSpec (official Haskell test vectors)
#
# This script clones cardano-ledger at the pinned SHA, applies a minimal patch
# to the ImpSpec conformance machinery, and runs the official conformance test
# suite to collect CBOR test vectors.
#
# The patch makes the conformance hooks dump inputs + Haskell expected output
# for EVERY test case (not just Haskell/Agda divergences).  This produces
# authoritative test vectors: the inputs are generated by the official
# constrained-generator framework and the expected outputs are the Haskell
# STS results.
#
# Two ImpSpec paths are patched:
#
#   1. ExecSpecRule/Core.hs — testConformance (QuickCheck property tests)
#      Captures: ENACT, DELEG, GOVCERT, POOL, CERT, CERTS, GOV
#
#   2. Imp/Core.hs — conformanceHook (hook-based ImpSpec tests)
#      Captures: NEWEPOCH (epoch boundaries), LEDGER (tx submissions)
#
# ## Output layout (5 files per test-case directory; st_out is optional)
#
#   content/<Rule>/<test_name>/conformance_dump_ctx.cbor     — context
#   content/<Rule>/<test_name>/conformance_dump_env.cbor     — environment
#   content/<Rule>/<test_name>/conformance_dump_st.cbor      — initial state
#   content/<Rule>/<test_name>/conformance_dump_sig.cbor     — signal
#   content/<Rule>/<test_name>/conformance_dump_st_out.cbor  — Haskell result
#
# ctx/env are CBOR null (0xF6) for NEWEPOCH because the rule uses () for both.
# st_out is absent when the STS rule rejects the transition.

set -euo pipefail

SOURCES_TOML="" WORK_DIR="" TARBALL=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --sources-toml) SOURCES_TOML="$2"; shift 2 ;;
        --work-dir)     WORK_DIR="$2";     shift 2 ;;
        --tarball)      TARBALL="$2";      shift 2 ;;
        *)              echo "Unknown arg: $1" >&2; exit 1 ;;
    esac
done

log() { echo "[capture-ledger-rules] $*"; }

# ── Write a stub tarball when no toolchain is available ───────────────────────
write_stub() {
    local content_dir="$1"
    cat > "${content_dir}/README.txt" <<'EOF'
ledger-rules — stub placeholder (no Haskell toolchain found)

This area requires GHC 9.6.x + cabal 3.10.x to populate.
See: scripts/regenerate-conformance-corpus/capture-ledger-rules.sh

Vector format: 5 files per test-case directory (st_out is optional)
  <Rule>/<test_name>/conformance_dump_ctx.cbor     — context (CBOR null for NEWEPOCH)
  <Rule>/<test_name>/conformance_dump_env.cbor     — environment (CBOR null for NEWEPOCH)
  <Rule>/<test_name>/conformance_dump_st.cbor      — initial state (e.g. NewEpochState)
  <Rule>/<test_name>/conformance_dump_sig.cbor     — signal (EpochNo for NEWEPOCH)
  <Rule>/<test_name>/conformance_dump_st_out.cbor  — Haskell STS result (when present)

The Phase 4 test module (ledger_rules_replay) skips gracefully until real
fixture directories are present.
EOF
    echo '{"__stub__": true}' > "${WORK_DIR}/hashes.json"
    tar -czf "${TARBALL}" -C "${content_dir}" .
    log "Placeholder tarball written: ${TARBALL}"
}

# ── Parse SHA from sources.toml ───────────────────────────────────────────────
SHA=$(awk '
    /^\[ledger-rules\]/ { in_section=1; next }
    /^\[/ { in_section=0 }
    in_section && /^sha/ { match($0, /\"([0-9a-f]+)\"/, arr); print arr[1]; exit }
' "${SOURCES_TOML}")
log "Target cardano-ledger SHA: ${SHA:-<not set>}"

# ── Check for cabal ───────────────────────────────────────────────────────────
HAS_CABAL=0
command -v cabal >/dev/null 2>&1 && HAS_CABAL=1

CONTENT_DIR="${WORK_DIR}/content"
mkdir -p "${CONTENT_DIR}"

if [[ $HAS_CABAL -eq 0 ]]; then
    log "STUB — cabal not found (GHC 9.6.x + cabal 3.10.x required)."
    write_stub "${CONTENT_DIR}"
    exit 0
fi

# ── Verify python3 for the patch script ──────────────────────────────────────
command -v python3 >/dev/null 2>&1 || { log "ERROR: python3 not found"; exit 1; }

# ── Full capture (requires Haskell toolchain) ─────────────────────────────────
[[ -n "$SHA" ]] || { log "ERROR: sha not set in ${SOURCES_TOML} under [ledger-rules]"; exit 1; }

CLONE_DIR="${WORK_DIR}/cardano-ledger-src"
log "Cloning IntersectMBO/cardano-ledger at ${SHA}..."
git clone --quiet --depth=1 "https://github.com/IntersectMBO/cardano-ledger.git" "${CLONE_DIR}"
git -C "${CLONE_DIR}" fetch --quiet --depth=1 origin "${SHA}"
git -C "${CLONE_DIR}" checkout --quiet "${SHA}"

# ── Apply the ImpSpec dump patch ──────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PATCH_SCRIPT="${SCRIPT_DIR}/patch-impspec-core.py"

EXEC_SPEC_CORE="${CLONE_DIR}/libs/cardano-ledger-conformance/src/Test/Cardano/Ledger/Conformance/ExecSpecRule/Core.hs"
IMP_CORE="${CLONE_DIR}/libs/cardano-ledger-conformance/test/Test/Cardano/Ledger/Conformance/Imp/Core.hs"

[[ -f "${PATCH_SCRIPT}" ]] || { log "ERROR: patch script not found: ${PATCH_SCRIPT}"; exit 1; }
[[ -f "${EXEC_SPEC_CORE}" ]] || { log "ERROR: ExecSpecRule/Core.hs not found at pinned SHA"; exit 1; }
[[ -f "${IMP_CORE}" ]] || { log "ERROR: Imp/Core.hs not found at pinned SHA"; exit 1; }

log "Applying ImpSpec dump patch..."
python3 "${PATCH_SCRIPT}" "${EXEC_SPEC_CORE}" "${IMP_CORE}"

# ── Build the patched conformance test suite ──────────────────────────────────
log "Building cardano-ledger-conformance:test:tests (this may take 30-45 min cold)..."
(
    cd "${CLONE_DIR}"
    cabal update
    cabal build cardano-ledger-conformance:test:tests 2>&1
)

# ── Run the patched conformance tests to collect CBOR vectors ─────────────────
#
# CONFORMANCE_CBOR_DUMP_PATH: triggers both patched hooks to emit CBOR files.
# --quickcheck-tests 10: limits QuickCheck iterations per property to 10 so
#   the run completes within CI's 120 minute budget.
# --num-threads 1: sequential execution ensures the global IORef counter gives
#   unique names (the counter is designed for single-threaded use).
# || true: don't abort if some tests report divergence failures — the files
#   are already written.  Build failures are caught by 'cabal build' above.

DUMP_DIR="${WORK_DIR}/dumps"
mkdir -p "${DUMP_DIR}"

log "Running cardano-ledger-conformance:test:tests → ${DUMP_DIR}..."
(
    cd "${CLONE_DIR}"
    CONFORMANCE_CBOR_DUMP_PATH="${DUMP_DIR}" \
    cabal test cardano-ledger-conformance:test:tests \
        --test-options "--quickcheck-tests 10 --num-threads 1" \
        2>&1
) || log "WARN: Some conformance tests may have reported failures (vectors are still collected)"

# ── Verify we got at least some vectors ───────────────────────────────────────
VECTOR_COUNT=$(find "${DUMP_DIR}" -name "conformance_dump_st.cbor" 2>/dev/null | wc -l | tr -d ' ')
if [[ "${VECTOR_COUNT}" -eq 0 ]]; then
    log "ERROR: No CBOR vectors were written to ${DUMP_DIR}."
    log "       Check the cabal output above for build or runtime errors."
    exit 1
fi
log "Found ${VECTOR_COUNT} raw vector state files under ${DUMP_DIR}"

# ── Mirror test-case directories into content structure ───────────────────────
#
# The hooks write:
#   <DUMP_DIR>/<Rule>/<test_name>/conformance_dump_{ctx,env,st,sig}.cbor
#   <DUMP_DIR>/<Rule>/<test_name>/conformance_dump_st_out.cbor  (optional)
#
# Copy each complete test-case directory verbatim into CONTENT_DIR.

REQUIRED_FILES=(
    "conformance_dump_ctx.cbor"
    "conformance_dump_env.cbor"
    "conformance_dump_st.cbor"
    "conformance_dump_sig.cbor"
)

OPTIONAL_FILES=(
    "conformance_dump_st_out.cbor"
)

TEST_CASE_COUNT=0
RULE_COUNT=0

for rule_dir in "${DUMP_DIR}"/*/; do
    [[ -d "${rule_dir}" ]] || continue
    rule=$(basename "${rule_dir}")
    rule_found=0

    for test_case_dir in "${rule_dir}"*/; do
        [[ -d "${test_case_dir}" ]] || continue
        test_name=$(basename "${test_case_dir}")

        # Verify all 4 required files are present.
        all_present=1
        for req in "${REQUIRED_FILES[@]}"; do
            if [[ ! -f "${test_case_dir}/${req}" ]]; then
                log "WARN: ${rule}/${test_name}: missing ${req} — skipping"
                all_present=0
                break
            fi
        done
        [[ $all_present -eq 0 ]] && continue

        # Copy required files into the content tree.
        dest="${CONTENT_DIR}/${rule}/${test_name}"
        mkdir -p "${dest}"
        for req in "${REQUIRED_FILES[@]}"; do
            cp "${test_case_dir}/${req}" "${dest}/"
        done

        # Copy optional files (st_out) when present.
        for opt in "${OPTIONAL_FILES[@]}"; do
            if [[ -f "${test_case_dir}/${opt}" ]]; then
                cp "${test_case_dir}/${opt}" "${dest}/"
            fi
        done

        ((TEST_CASE_COUNT++))
        rule_found=1
    done

    [[ $rule_found -eq 1 ]] && ((RULE_COUNT++))
done

log "Captured ${TEST_CASE_COUNT} test cases across ${RULE_COUNT} rule(s)"

if [[ $TEST_CASE_COUNT -eq 0 ]]; then
    log "ERROR: Dump directory had files but no complete 4-file test-case directories."
    exit 1
fi

# ── Emit hashes ───────────────────────────────────────────────────────────────
{
    echo "{"
    first=1
    while IFS= read -r -d '' f; do
        hash=$(sha256sum "$f" | awk '{print $1}')
        rel="${f#"${CONTENT_DIR}/"}"
        [[ $first -eq 1 ]] && first=0 || printf ","
        printf '\n  "%s": "sha256:%s"' "$rel" "$hash"
    done < <(find "${CONTENT_DIR}" -name "*.cbor" -type f -print0 | sort -z)
    echo ""
    echo "}"
} > "${WORK_DIR}/hashes.json"

tar -czf "${TARBALL}" -C "${CONTENT_DIR}" .
log "Tarball written: ${TARBALL} (${TEST_CASE_COUNT} test cases, ${RULE_COUNT} rules)"
