#!/usr/bin/env python3
"""Vendor IntersectMBO's plutus-tx-compiled example scripts as a JSON fixture.

Why
---
Every Plutus validator on the devnet was `always-true` or `always-false`, and
an always-true validator never reads the ScriptContext. So the gate proved that
dugite *builds* a context, resolves the right redeemer pointer, charges a
budget and reaches cardano-node's accept/reject verdict — but nothing ever
inspected the context's *contents*. A wrong field, a wrong list order or a
missing entry passed every Plutus test in the suite. #772 was exactly that bug
class (#969).

Authoritativeness is the whole point, which is why this reads cardano-ledger
rather than compiling something ourselves with Aiken. Aiken is a third-party
compiler: if its stdlib's view of the ScriptContext and dugite's construction
share a misunderstanding, an Aiken-built validator agrees with the bug and
passes. That conclusion is already on record from #772 — "aiken parity is
circular" (#970).

`Test.Cardano.Ledger.Plutus.Examples` is generated by
`plutus-preprocessor:plutus-preprocessor` from `plutus-tx` source using
`plutus-tx-plugin`, and the resulting bytes are CHECKED IN. That makes it
route 1 of #969's preference order — a pinned upstream artifact — with no GHC
anywhere in the devnet path.

What comes out
--------------
14 scripts x 4 language versions (V1/V2/V3/V4), each with the script bytes AND
the `ScriptHash` upstream recorded beside them in a comment. The hash is what
makes this a real oracle rather than a blob: it is computed by cardano-ledger
over the same bytes, so a dugite hash mismatch is a defect in dugite's script
hashing or its language-tag prefix, independent of anything we wrote.

Several of these do inspect the context — `purposeIsWellformedNoDatum` alone
pattern-matches all six Conway script purposes and asserts the subject of each
appears in the corresponding `TxInfo` field (mint value, inputs, withdrawals,
certificates, votes).

Usage
-----
    scripts/regenerate-conformance-corpus/extract-plutus-examples.py \
        [--ref <cardano-ledger-git-ref>] [--out <path>]
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

SOURCE_PATH = "libs/cardano-ledger-core/testlib/Test/Cardano/Ledger/Plutus/Examples.hs"
RAW = "https://raw.githubusercontent.com/IntersectMBO/cardano-ledger/{ref}/{path}"

# The pinned ref. Bump deliberately, re-run, and commit the regenerated JSON —
# the script hashes are expected to change whenever plutus-tx's codegen does,
# and a silent drift is exactly what a committed fixture is for.
DEFAULT_REF = "4f7cb2d6874df70561e32147084ed82cee773e8a"

# Each `name :: SLanguage l -> Plutus l` block holds one arm per language, and
# each arm is preceded by a `-- ScriptHash "..."` comment. Parsing the comment
# is deliberate: it is upstream's own answer, not ours.
FN_HEADER = re.compile(r"^(\w+) ::\s*\n?\s*SLanguage l -> Plutus l\s*$", re.M)
ARM = re.compile(
    r'--\s*ScriptHash "([0-9a-f]{56})".*?'
    r"SPlutus(V\d)\s*->\s*\n((?:\s*[\[,]\s*\"[0-9a-f]*\"\s*\n)+\s*\])",
    re.S,
)
HEX = re.compile(r'"([0-9a-f]*)"')


def fetch(ref: str) -> str:
    # curl, not urllib: the rest of the corpus tooling shells out to curl, and
    # python's urllib uses its own CA bundle, which is not configured on every
    # dev machine (observed: CERTIFICATE_VERIFY_FAILED on stock macOS python).
    url = RAW.format(ref=ref, path=SOURCE_PATH)
    r = subprocess.run(
        ["curl", "-sSfL", url], capture_output=True, text=True, check=False
    )
    if r.returncode != 0:
        raise SystemExit(f"curl failed for {url}: {r.stderr.strip()}")
    return r.stdout


def parse(src: str) -> list[dict]:
    headers = [(m.group(1), m.start()) for m in FN_HEADER.finditer(src)]
    if not headers:
        raise SystemExit(
            "no `name :: SLanguage l -> Plutus l` blocks found — upstream "
            "changed the generated module's shape; fix this parser rather "
            "than hand-editing the JSON"
        )
    out: list[dict] = []
    for i, (name, start) in enumerate(headers):
        end = headers[i + 1][1] if i + 1 < len(headers) else len(src)
        block = src[start:end]
        langs = {}
        for m in ARM.finditer(block):
            script_hash, lang, body = m.group(1), m.group(2), m.group(3)
            hex_bytes = "".join(HEX.findall(body))
            if not hex_bytes:
                raise SystemExit(f"{name}/{lang}: empty script body")
            langs[lang] = {"script_hex": hex_bytes, "script_hash": script_hash}
        if not langs:
            raise SystemExit(f"{name}: no language arms parsed")
        out.append({"name": name, "languages": langs})
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--ref", default=DEFAULT_REF)
    ap.add_argument(
        "--out",
        default="tests/conformance/upstream/plutus-examples.json",
        type=Path,
    )
    args = ap.parse_args()

    scripts = parse(fetch(args.ref))

    # Refuse to write a fixture that is quietly smaller than the last one. A
    # parser that silently matches fewer arms after an upstream reformat would
    # otherwise shrink coverage without failing anything.
    total_arms = sum(len(s["languages"]) for s in scripts)
    if len(scripts) < 14 or total_arms < 14 * 3:
        raise SystemExit(
            f"only parsed {len(scripts)} scripts / {total_arms} language arms; "
            "upstream has at least 14 x 3. Refusing to shrink the fixture."
        )

    doc = {
        "_comment": (
            "GENERATED by scripts/regenerate-conformance-corpus/"
            "extract-plutus-examples.py — do not hand-edit. Vendored from "
            "IntersectMBO/cardano-ledger " + SOURCE_PATH + ", which is itself "
            "generated from plutus-tx source by plutus-preprocessor using "
            "plutus-tx-plugin. script_hash is UPSTREAM's value, recorded "
            "beside the bytes in the generated module; dugite must reproduce "
            "it (#969/#970)."
        ),
        "source_repo": "IntersectMBO/cardano-ledger",
        "source_ref": args.ref,
        "source_path": SOURCE_PATH,
        "scripts": scripts,
    }

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(doc, indent=2, sort_keys=False) + "\n")
    print(
        f"wrote {args.out}: {len(scripts)} scripts, {total_arms} language arms",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
