//! Build script that materialises per-test `#[test]` functions for the
//! UPLC evaluation conformance corpus.
//!
//! When the `upstream-conformance` (or its alias `conformance`) cargo feature
//! is enabled, walks the unified fixture root and emits one test function per
//! leaf directory containing a `*.uplc` file. The harness itself lives in
//! `tests/conformance.rs`; this script only generates the entries it includes
//! via `include!(concat!(env!("OUT_DIR"), "/generated_conformance_tests.rs"))`.
//!
//! **Corpus location** (searched in order):
//!   1. `$DUGITE_UPSTREAM_FIXTURES_DIR/plutus/` — explicit override.
//!   2. `<workspace_root>/tests/conformance/upstream/fixtures/plutus/` —
//!      populated by `cargo xtask download-upstream-fixtures [--area plutus]`.
//!
//! When the feature is off, emits an empty file so the include macro still
//! compiles.
//!
//! Skip list: `tests/conformance_skip.txt`, one path per line (paths are
//! relative to the corpus root and use forward slashes, e.g.
//! `builtin/semantics/droplist/droplist-09`). Lines starting with `#` are
//! comments.

use std::collections::BTreeSet;
use std::env;
use std::ffi::OsStr;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let crate_root = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let out_file = out_dir.join("generated_conformance_tests.rs");

    let conformance_enabled = env::var_os("CARGO_FEATURE_UPSTREAM_CONFORMANCE").is_some()
        || env::var_os("CARGO_FEATURE_CONFORMANCE").is_some();

    if !conformance_enabled {
        fs::write(&out_file, "// conformance feature disabled\n")
            .expect("write empty generated_conformance_tests.rs");
        return;
    }

    // Resolve corpus root: env override → workspace unified fixture root.
    let corpus_root = if let Ok(dir) = env::var("DUGITE_UPSTREAM_FIXTURES_DIR") {
        PathBuf::from(dir).join("plutus")
    } else {
        workspace_root(&crate_root)
            .join("tests")
            .join("conformance")
            .join("upstream")
            .join("fixtures")
            .join("plutus")
    };

    let skip_path = crate_root.join("tests").join("conformance_skip.txt");

    println!("cargo:rerun-if-changed={}", skip_path.display());
    println!("cargo:rerun-if-changed={}", corpus_root.display());
    println!("cargo:rerun-if-changed=build.rs");

    let skip = load_skip_list(&skip_path);

    let mut entries: Vec<TestEntry> = Vec::new();
    if corpus_root.is_dir() {
        collect_tests(&corpus_root, &corpus_root, &mut entries);
    } else {
        // No corpus on disk → emit a single sentinel test that prints
        // an instructive message rather than silently passing 0 tests.
        let body = r#"// conformance corpus not downloaded
#[test]
fn conformance_corpus_missing() {
    eprintln!(
        "Plutus conformance corpus not found. Run \
         `cargo xtask download-upstream-fixtures --area plutus` \
         (or `just download-upstream-fixtures-area plutus`) to populate \
         tests/conformance/upstream/fixtures/plutus/, then re-run with \
         `cargo test -p dugite-uplc --features conformance --test conformance`."
    );
}
"#;
        fs::write(&out_file, body).expect("write sentinel generated tests");
        return;
    }

    entries.sort_by(|a, b| a.test_name.cmp(&b.test_name));

    // Cross-check skip list: every entry in conformance_skip.txt must
    // correspond to a test we actually discovered. Stale skip-list
    // entries hide regressions, so we fail the build on them.
    let discovered_rel: BTreeSet<&str> =
        entries.iter().map(|e| e.rel_dir_forward.as_str()).collect();
    let stale: Vec<&String> = skip
        .iter()
        .filter(|s| !discovered_rel.contains(s.as_str()))
        .collect();
    if !stale.is_empty() {
        panic!(
            "tests/conformance_skip.txt contains entries with no matching test directory:\n  - {}",
            stale
                .iter()
                .map(|s| s.as_str())
                .collect::<Vec<_>>()
                .join("\n  - ")
        );
    }

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by crates/dugite-uplc/build.rs — do not edit.\n");
    out.push_str("// Source: tests/conformance/ (downloaded from IntersectMBO/plutus).\n\n");

    for entry in &entries {
        let ignored = skip.contains(&entry.rel_dir_forward);
        let ignore_attr = if ignored { "#[ignore]\n" } else { "" };
        // We pass the corpus-relative path so the runner can produce
        // informative failure messages without leaking absolute paths.
        out.push_str(&format!(
            "{ignore_attr}#[test]\nfn {name}() {{\n    \
             run_conformance_test(\n        {rel:?},\n        \
             include_str!({input:?}),\n        \
             include_str!({expected:?}),\n        \
             include_str!({budget:?}),\n    );\n}}\n\n",
            name = entry.test_name,
            rel = entry.rel_dir_forward,
            input = entry.uplc_path.display().to_string(),
            expected = entry.expected_path.display().to_string(),
            budget = entry.budget_path.display().to_string(),
        ));
    }

    fs::write(&out_file, out).expect("write generated_conformance_tests.rs");
}

struct TestEntry {
    /// Sanitised Rust identifier for the `#[test]` fn name.
    test_name: String,
    /// Forward-slashed path relative to the corpus root (used for skip
    /// list lookup and runner diagnostics).
    rel_dir_forward: String,
    /// Absolute path to the `.uplc` input.
    uplc_path: PathBuf,
    /// Absolute path to the `.uplc.expected` golden.
    expected_path: PathBuf,
    /// Absolute path to the `.uplc.budget.expected` golden.
    budget_path: PathBuf,
}

fn collect_tests(root: &Path, dir: &Path, out: &mut Vec<TestEntry>) {
    let Ok(read) = fs::read_dir(dir) else {
        return;
    };

    for ent in read.flatten() {
        let path = ent.path();
        if path.is_dir() {
            collect_tests(root, &path, out);
            continue;
        }
        // Match exactly *.uplc (NOT *.uplc.expected / *.uplc.budget.expected).
        if path.extension().and_then(OsStr::to_str) != Some("uplc") {
            continue;
        }
        let stem_ok = path
            .file_name()
            .and_then(OsStr::to_str)
            .map(|n| n.ends_with(".uplc") && !n.ends_with(".expected"))
            .unwrap_or(false);
        if !stem_ok {
            continue;
        }
        let parent = path
            .parent()
            .expect("uplc file must have a parent directory");
        let rel_dir = parent
            .strip_prefix(root)
            .expect("walk stays inside corpus root");
        let rel_dir_forward = rel_dir
            .to_string_lossy()
            .replace(std::path::MAIN_SEPARATOR, "/");

        let test_name = sanitise_test_name(&rel_dir_forward);

        let expected_path = path.with_file_name(format!(
            "{}.expected",
            path.file_name().and_then(OsStr::to_str).unwrap_or("")
        ));
        let budget_path = path.with_file_name(format!(
            "{}.budget.expected",
            path.file_name().and_then(OsStr::to_str).unwrap_or("")
        ));

        out.push(TestEntry {
            test_name,
            rel_dir_forward,
            uplc_path: path.clone(),
            expected_path,
            budget_path,
        });
    }
}

/// Map a corpus-relative directory like `builtin/semantics/addInteger/addInteger-1`
/// to a Rust identifier `builtin_semantics_addinteger_addinteger_1`.
fn sanitise_test_name(rel_forward: &str) -> String {
    let mut s: String = rel_forward
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect::<String>()
        .to_lowercase();
    // Cargo test names must not start with a digit.
    if s.chars()
        .next()
        .map(|c| c.is_ascii_digit())
        .unwrap_or(false)
    {
        s.insert(0, '_');
    }
    s
}

/// Walk upward from `start` until we find a Cargo.toml containing `[workspace]`.
fn workspace_root(start: &Path) -> PathBuf {
    let mut dir = start.to_path_buf();
    loop {
        let candidate = dir.join("Cargo.toml");
        if candidate.exists()
            && fs::read_to_string(&candidate)
                .map(|s| s.contains("[workspace]"))
                .unwrap_or(false)
        {
            return dir;
        }
        if !dir.pop() {
            panic!("workspace root not found from {}", start.display());
        }
    }
}

fn load_skip_list(path: &Path) -> BTreeSet<String> {
    let mut out = BTreeSet::new();
    let Ok(raw) = fs::read_to_string(path) else {
        return out;
    };
    for line in raw.lines() {
        let trimmed = line.split('#').next().unwrap_or("").trim();
        if trimmed.is_empty() {
            continue;
        }
        out.insert(trimmed.to_string());
    }
    out
}
