#!/usr/bin/env bash
# KES round: expiry stops forging; opcert future-period and counter-rotation  (#1037)
# semantics vs Haskell peers. Adopted from upstream cardano-node-tests
# test_kes.py.
#
# WHY THIS ROUND EXISTS
# ---------------------
# No standing round ever lets a KES key actually die: the checked-in genesis
# defaults (slotsPerKESPeriod=129600, maxKESEvolutions=62) put natural expiry
# ~36 hours out. So the CannotForge / KesExpired / opcert-counter code paths
# in crates/dugite-consensus/src/praos.rs and crates/dugite-node/src/forge.rs
# had never executed against a real Haskell peer. This round uses the
# checked-in `config/spec/overlays/kes-short.json` overlay
# (slotsPerKESPeriod=120, maxKESEvolutions=10) so dugite-bp's KES key dies at
# slot 1200 (epoch 3 at epochLength=400) inside a normal round budget.
#
# TERMINAL ROUND. Runs its own two-forger devnet and tears it down at the
# end — dugite-bp's keys get rotated ad hoc through five different opcerts,
# so the devnet this round leaves behind is not meaningful for any other
# round to reuse.
#
# CARDANO-BP'S KES KEY DIES AT THE SAME SLOT
# -------------------------------------------
# Both pools are generated by the same `create-testnet-data` call, so
# cardano-bp's ORIGINAL KES key evolves out at slot 1200 too — if left alone
# it would go dark at the same moment as dugite-bp, and step 2's "cardano-bp
# keeps forging" control group would be lying dead in the water for the same
# reason as the thing under test, which proves nothing.
#
# Fix: step A, run once close to (but safely before) the slot-1200 deadline,
# issues cardano-bp a FRESH KES key + opcert at whatever KES period is
# current at that moment and restarts cardano-bp with it. Waiting until close
# to the deadline (rather than refreshing early) matters: an opcert issued at
# period P is valid through period P + maxKESEvolutions - 1, i.e. up to slot
# (P + 10) * 120. Refreshing early (say period 1, slot ~150) would only buy
# cardano-bp until slot ~1320 — not enough headroom for a ~20 minute round.
# Refreshing near slot ~1000-1150 (period ~8-9) buys headroom to slot
# ~2160-2280, comfortably past every later step.
#
# THE OPCERT-COUNTER FILE, AND WHY STEPS 3/4 NEVER TOUCH THE REAL ONE
# ----------------------------------------------------------------------
# cardano-cli tracks pool1's next-to-issue counter in
# $LD_KEYS/pool1/opcert.counter and auto-increments it on every
# `issue-op-cert` call. The over-increment check Haskell (and dugite's own
# receiving-side praos.rs) enforces compares a NEW counter against the last
# counter the NETWORK has actually seen ON A VALIDATED HEADER for that pool —
# not against whatever the local counter FILE's bookkeeping says.
#
# Steps 3 and 4 both issue opcerts that dugite-bp can never get accepted
# on-chain (step 3 is gated by the KES-period-not-yet-valid check before
# forge_block is ever called; step 4 is deliberately rejected for its
# counter). So from the network's point of view the counter last actually
# used is still whatever the setup opcert carried (call it C0) — the ones
# steps 3/4 issue are NEVER seen by any peer as a produced header, so they
# have no effect on that ground truth.
#
# If steps 3 and 4 consumed the REAL counter file in sequence, step 5's
# "valid +1 rotation" would end up with counter = C0+3 or higher relative to
# C0 — which Haskell would ALSO reject as an over-increment, breaking the
# one step in this round that is supposed to succeed. So steps 3 and 4 each
# work against their OWN throwaway COPY of the counter file (never written
# back); step 4's copy is consumed twice (one throwaway issuance, one real)
# to get exactly C0+2 in the cert dugite-bp actually loads. Only step 5
# touches the real $LD_KEYS/pool1/opcert.counter, so its cert is a genuine
# C0+1 — a real, Haskell-acceptable rotation.
#
# Usage:
#   ./kes-round.sh                # full round (~25-30 min), own devnet
#   KES_SKIP_SETUP=1 ./kes-round.sh   # reuse a running two-forger + short-KES devnet
set +e
[ -n "${ZSH_VERSION:-}" ] && { unsetopt ERR_EXIT ERR_RETURN 2>/dev/null || true; }

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 2

SKIP_SETUP="${KES_SKIP_SETUP:-0}"
OBS_WINDOW="${KES_OBS_WINDOW:-120}"
FAILURES=0

step() { echo; echo "########## $* ##########"; date -u +%H:%M:%SZ; }
ok()   { printf '\033[0;32m[PASS]\033[0m %s\n' "$*"; }
bad()  { printf '\033[0;31m[FAIL]\033[0m %s\n' "$*"; FAILURES=$((FAILURES + 1)); }
note() { printf '\033[0;36m[NOTE]\033[0m %s\n' "$*"; }
# INCONCLUSIVE = the predicate could not be evaluated, so its PASS would have
# been vacuous. Counted as a failure on purpose (#953: a gate must hard-fail on
# evidence that was never produced) but labelled distinctly so an operator can
# tell "dugite-bp did the wrong thing" from "dugite-bp was never measured".
inconc() { printf '\033[0;33m[INCONCLUSIVE]\033[0m %s\n' "$*"; FAILURES=$((FAILURES + 1)); }

# Count dugite-bp leadership checks recorded after a log mark.
#
# #1055/#1057: "dugite-bp forged 0 blocks in the post-expiry window" is
# trivially true for a forger that is not even RUNNING leadership checks — and
# that is exactly what #1057 produced (the BP wedged on its own fork, its
# catch-up gate silently skipping every slot before the KES gate could be
# reached). Without this discriminator the KES round reported a clean PASS for a
# node that had been dead for 20 minutes for an unrelated reason.
dbp_leader_checks_since() {
    local mark="$1"
    awk -v m="$mark" 'NR > m && /TraceStartLeadershipCheck/ {c++} END{print c+0}' \
        "$LD_LOGS/dugite-bp.log" 2>/dev/null
}

if [ "$SKIP_SETUP" -eq 0 ]; then
    step "setup + run (two-forger mode + short-KES genesis overlay)"
    ./stop.sh >/dev/null 2>&1
    LD_TWO_FORGERS=1 LD_SHELLEY_SPEC_EXTRA="$PWD/config/spec/overlays/kes-short.json" \
        ./setup.sh >/dev/null 2>&1 || { echo "SETUP FAILED"; exit 2; }
    # NOT `./run.sh | tail` — a pipeline's exit status is the LAST command's;
    # see two-forger-round.sh's identical note (#957 finding).
    if ! ./run.sh > "state/kes-run.log" 2>&1; then
        echo "RUN FAILED — last 20 lines:"
        tail -20 "state/kes-run.log"
        exit 2
    fi
    tail -12 "state/kes-run.log"
fi

. ./lib/common.sh
. ./lib/expect-log-errors.sh
set +e

[ -f "$LD_GENESIS/.two-forgers" ] || {
    echo "REFUSING TO RUN: $LD_GENESIS/.two-forgers is absent, so this is a"
    echo "single-forger devnet. cardano-bp would never be forging in the first"
    echo "place, and every assertion below needs it as a live control group."
    exit 2
}

ALLOWLIST="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/kes-round.allowed-errors"
[ -f "$ALLOWLIST" ] || { echo "missing kes-round.allowed-errors next to kes-round.sh"; exit 2; }

WORK="$LD_STATE/kes-round"
mkdir -p "$WORK"

EVIDENCE_DIR="$LD_EVIDENCE/$(date -u +%Y%m%dT%H%M%SZ)"
mkdir -p "$EVIDENCE_DIR"
CSV="$EVIDENCE_DIR/kes-round.csv"
echo "ts,step,outcome,detail" > "$CSV"
csv_row() {
    printf '%s,%s,%s,%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$1" "$2" "${3//,/;}" >> "$CSV"
}
# Write one terminal PASS/FAIL row for a step, based on whether FAILURES grew
# during it (mirrors chaos/lib.sh's chaos_record ts/label/result/detail shape
# — the closest existing evidence-CSV convention in this repo, since
# two-forger-round.sh itself only prints ok/bad and writes no CSV).
step_row() {
    local label="$1" before="$2"
    if [ "$FAILURES" -eq "$before" ]; then
        csv_row "$label" PASS "ok"
    else
        csv_row "$label" FAIL "$((FAILURES - before)) assertion(s) failed"
    fi
}

# ---------------------------------------------------------------- constants --
# Must match config/spec/overlays/kes-short.json exactly.
SLOTS_PER_KES=120
MAX_KES_EVOLUTIONS=10
KES_DEATH_SLOT=$((MAX_KES_EVOLUTIONS * SLOTS_PER_KES))   # 1200

# ---------------------------------------------------------------- helpers ----
tip_json() { cardano-cli query tip --testnet-magic "$LD_MAGIC" --socket-path "$1" 2>/dev/null; }
tip_field() { tip_json "$1" | jq -r "$2 // empty" 2>/dev/null; }

cur_slot() {
    local s
    s=$(tip_field "$LD_CARDANO_ARBITER_SOCK" .slot)
    [ -z "$s" ] && s=$(tip_field "$LD_RELAY_SOCK" .slot)
    echo "${s:-0}"
}
cur_period() { echo $(( $(cur_slot) / SLOTS_PER_KES )); }

wait_until_slot() {
    local target="$1" deadline="$2" label="$3" s
    while :; do
        s=$(cur_slot)
        [ "${s:-0}" -ge "$target" ] && return 0
        [ "$(date +%s)" -ge "$deadline" ] && {
            note "$label: timed out waiting for slot $target (stuck at ${s:-?})"
            return 1
        }
        sleep 10
    done
}

dbp_forge_count() { awk '/TraceForgedBlock/{c++} END{print c+0}' "$LD_LOGS/dugite-bp.log" 2>/dev/null; }
cbp_forge_count() { awk '/Forge\.Loop\.AdoptedBlock/{c++} END{print c+0}' "$LD_LOGS/cardano-bp.log" 2>/dev/null; }

# count_matching_since <ere> <file> <mark> — lines matching <ere> after line
# <mark>. awk-only (never `grep -c ... || echo 0`): chaos/lib.sh documents
# that idiom as broken (grep -c prints "0" AND exits 1 on no-match, so
# `|| echo 0` appends a SECOND "0" line and every arithmetic test on the
# result dies with "integer expected").
count_matching_since() {
    local re="$1" file="$2" mark="$3"
    [ -f "$file" ] || { echo 0; return 0; }
    tail -n +"$((mark + 1))" "$file" 2>/dev/null \
        | awk -v re="$re" 'BEGIN{c=0} $0 ~ re {c++} END{print c+0}'
}

# forged_hashes_since <mark> — dugite-bp TraceForgedBlock hashes after <mark>,
# deduped. Tolerates both quoted and unquoted tracing field rendering.
forged_hashes_since() {
    local mark="$1"
    tail -n +"$((mark + 1))" "$LD_LOGS/dugite-bp.log" 2>/dev/null \
        | grep 'TraceForgedBlock' \
        | grep -oE 'block_hash="?[0-9a-f]+"?' \
        | tr -d '"' \
        | sed 's/^block_hash=//' \
        | sort -u
}

# Resolve dugite-bp's REAL node PID by command line, never the pidfile: on
# macOS the node runs under `caffeinate -dimsu`, and the pidfile can name the
# wrapper (see lib/common.sh's write_node_pidfile and
# chaos/kill-9-mid-forge.sh's identical warning). SIGTERM only, never -9 — a
# killed dugite-node corrupts the append-only ImmutableDB.
stop_dugite_bp() {
    local pid
    pid=$(pgrep -f "dugite-node run .*dugite-bp" | head -1)
    [ -z "$pid" ] && return 0
    kill "$pid" 2>/dev/null
    local w=0
    while kill -0 "$pid" 2>/dev/null && [ "$w" -lt 40 ]; do sleep 1; w=$((w + 1)); done
    return 0
}

# restart_dugite_bp_with_creds <kes_skey> <opcert> — stop, install the new
# credentials into the paths restart-dugite-bp.sh hardcodes
# ($LD_KEYS/pool1/{kes.skey,opcert.cert}), then reuse that script (also used
# by two-forger-round.sh Round 3 / step 8) rather than hand-maintaining a
# second copy of dugite-bp's launch flags.
restart_dugite_bp_with_creds() {
    local kes_skey="$1" opcert="$2"
    stop_dugite_bp
    cp "$kes_skey" "$LD_KEYS/pool1/kes.skey"
    cp "$opcert"   "$LD_KEYS/pool1/opcert.cert"
    ../../.claude/skills/devnet-validate/scripts/restart-dugite-bp.sh >/dev/null 2>&1
}

# restart_cardano_bp <kes_skey> <opcert> — cardano-node is launched WITHOUT a
# caffeinate wrapper (see run.sh), so state/cardano-bp.pid already names the
# real process; no pgrep resolution needed. SIGTERM only.
restart_cardano_bp() {
    local kes_skey="$1" opcert="$2" pid
    pid=$(cat "$LD_STATE/cardano-bp.pid" 2>/dev/null)
    if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
        kill "$pid" 2>/dev/null
        local w=0
        while kill -0 "$pid" 2>/dev/null && [ "$w" -lt 40 ]; do sleep 1; w=$((w + 1)); done
    fi
    rm -f "$LD_CARDANO_BP_SOCK"
    cardano-node run \
        --config        "$LD_CONFIG/cardano-bp.config.json" \
        --topology      "$LD_CONFIG/cardano-bp.topology.json" \
        --database-path "$LD_STATE/cardano-bp.db" \
        --socket-path   "$LD_CARDANO_BP_SOCK" \
        --host-addr     127.0.0.1 \
        --port          "$LD_CARDANO_BP_PORT" \
        --shelley-kes-key                 "$kes_skey" \
        --shelley-vrf-key                 "$LD_KEYS/pool2/vrf.skey" \
        --shelley-operational-certificate "$opcert" \
        >> "$LD_LOGS/cardano-bp.log" 2>&1 &
    echo $! > "$LD_STATE/cardano-bp.pid"
    wait_for_socket "$LD_CARDANO_BP_SOCK" 90
}

# issue_pool1_opcert <period> <counter_file> <out_skey> <out_vkey> <out_cert>
# Fresh KES key + opcert for pool1 against an EXPLICIT counter file — callers
# decide whether that's the real $LD_KEYS/pool1/opcert.counter (step 5 only)
# or a throwaway copy (steps 3/4 — see header comment).
issue_pool1_opcert() {
    local period="$1" counter_file="$2" out_skey="$3" out_vkey="$4" out_cert="$5"
    cardano-cli conway node key-gen-KES \
        --verification-key-file "$out_vkey" \
        --signing-key-file "$out_skey" >>"$WORK/opcert.err" 2>&1 || return 1
    cardano-cli conway node issue-op-cert \
        --kes-verification-key-file "$out_vkey" \
        --cold-signing-key-file "$LD_KEYS/pool1/cold.skey" \
        --operational-certificate-issue-counter-file "$counter_file" \
        --kes-period "$period" \
        --out-file "$out_cert" >>"$WORK/opcert.err" 2>&1
}

# ============================================================ STEP 1 =========
F0=$FAILURES
step "1. baseline — both pools forging (>=3 blocks each)"
DEADLINE=$(( $(date +%s) + 300 ))
DBP_N=0; CBP_N=0
while [ "$(date +%s)" -lt "$DEADLINE" ]; do
    DBP_N=$(dbp_forge_count); CBP_N=$(cbp_forge_count)
    [ "${DBP_N:-0}" -ge 3 ] && [ "${CBP_N:-0}" -ge 3 ] && break
    sleep 10
done
note "baseline forge counts: dugite-bp=$DBP_N cardano-bp=$CBP_N (slot $(cur_slot))"
if [ "${DBP_N:-0}" -ge 3 ] && [ "${CBP_N:-0}" -ge 3 ]; then
    ok "both pools forged >=3 blocks"
else
    bad "baseline not reached within 300s: dugite-bp=$DBP_N cardano-bp=$CBP_N"
fi
step_row "1-baseline" "$F0"

# ============================================================ STEP A =========
F0=$FAILURES
step "A. pool2 (cardano-bp) KES refresh before dugite-bp's death at slot $KES_DEATH_SLOT"
REFRESH_LOW="${KES_P2_REFRESH_LOW:-1000}"
REFRESH_HIGH="${KES_P2_REFRESH_HIGH:-1150}"
if wait_until_slot "$REFRESH_LOW" "$(( $(date +%s) + 1800 ))" "pool2-refresh-wait"; then
    S_NOW=$(cur_slot)
    if [ "$S_NOW" -ge "$REFRESH_HIGH" ]; then
        bad "slot $S_NOW already past the refresh window ($REFRESH_LOW-$REFRESH_HIGH) — cardano-bp's original KES key may die alongside dugite-bp's at slot $KES_DEATH_SLOT, invalidating the control group in steps 2-5"
    fi
    P2_PERIOD=$(cur_period)
    cardano-cli conway node key-gen-KES \
        --verification-key-file "$WORK/p2-refresh.kes.vkey" \
        --signing-key-file "$WORK/p2-refresh.kes.skey" >"$WORK/p2.err" 2>&1
    cardano-cli conway node issue-op-cert \
        --kes-verification-key-file "$WORK/p2-refresh.kes.vkey" \
        --cold-signing-key-file "$LD_KEYS/pool2/cold.skey" \
        --operational-certificate-issue-counter-file "$LD_KEYS/pool2/opcert.counter" \
        --kes-period "$P2_PERIOD" \
        --out-file "$WORK/p2-refresh.opcert.cert" >>"$WORK/p2.err" 2>&1
    if [ -s "$WORK/p2-refresh.opcert.cert" ]; then
        ok "issued fresh pool2 opcert at kes-period $P2_PERIOD (slot $S_NOW; valid through ~slot $(( (P2_PERIOD + MAX_KES_EVOLUTIONS) * SLOTS_PER_KES )))"
        restart_cardano_bp "$WORK/p2-refresh.kes.skey" "$WORK/p2-refresh.opcert.cert"
        if [ -S "$LD_CARDANO_BP_SOCK" ]; then
            ok "cardano-bp restarted with refreshed KES credentials"
        else
            bad "cardano-bp did not come back up after the KES-refresh restart"
        fi
    else
        bad "failed to issue the pool2 refresh opcert: $(tail -3 "$WORK/p2.err" 2>/dev/null | tr '\n' ' ')"
    fi
else
    bad "never reached slot $REFRESH_LOW within budget — cannot refresh pool2's KES key"
fi
step_row "A-pool2-kes-refresh" "$F0"

# ============================================================ STEP 2 =========
F0=$FAILURES
step "2. dugite-bp KES expiry stops forging (natural expiry, no restart)"
wait_until_slot "$((KES_DEATH_SLOT - 50))" "$(( $(date +%s) + 1800 ))" "kes-death-wait"
note "at slot $(cur_slot), approaching KES death at slot $KES_DEATH_SLOT"
MARK_DBP=$(log_mark "$LD_LOGS/dugite-bp.log")
note "log mark taken at dugite-bp.log line $MARK_DBP (slot $(cur_slot))"

# RED-PROOF: the "zero new forges" predicate used below must be capable of
# detecting a LIVE forger, or it is vacuous. cardano-bp (refreshed in step A)
# is the control: if IT shows zero new blocks in a short window, the
# predicate — or the devnet — is broken, and the dugite-bp assertion that
# follows proves nothing.
CBP_CTRL_BEFORE=$(cbp_forge_count)
sleep 30
CBP_CTRL_AFTER=$(cbp_forge_count)
CBP_CTRL_DELTA=$((CBP_CTRL_AFTER - CBP_CTRL_BEFORE))
if [ "$CBP_CTRL_DELTA" -gt 0 ]; then
    ok "RED-PROOF: control window shows cardano-bp forged $CBP_CTRL_DELTA block(s) in 30s — the zero-forge predicate below is discriminating, not vacuous"
else
    bad "RED-PROOF FAILED: cardano-bp (the healthy control) forged 0 blocks in a 30s window — the zero-forge check below cannot be trusted"
fi

note "observation window: ${OBS_WINDOW}s from slot $(cur_slot)"
DBP_BEFORE=$(dbp_forge_count); CBP_BEFORE=$(cbp_forge_count)
sleep "$OBS_WINDOW"
DBP_AFTER=$(dbp_forge_count); CBP_AFTER=$(cbp_forge_count)
DBP_DELTA=$((DBP_AFTER - DBP_BEFORE))
CBP_DELTA=$((CBP_AFTER - CBP_BEFORE))
note "window deltas: dugite-bp=+$DBP_DELTA cardano-bp=+$CBP_DELTA"

# LIVENESS GATE (#1055/#1057) — evaluate BEFORE reading the zero-forge result.
#
# A forger that never ran a leadership check in the window cannot tell us
# anything about KES expiry. dugite's per-slot KES upper-bound gate lives at
# step 5c of `try_forge_block_at`, i.e. AFTER the silent catch-up gate at the
# top of that function — so a BP wedged behind its peers skips every slot
# without reaching (or logging) the KES check at all. #1057 produced exactly
# that, and this round's "forged 0 blocks" read as a KES pass for 20 minutes of
# a completely dead node.
DBP_CHECKS=$(dbp_leader_checks_since "$MARK_DBP")
note "dugite-bp leadership checks in window: $DBP_CHECKS"
if [ "$DBP_CHECKS" -eq 0 ]; then
    inconc "dugite-bp ran 0 leadership checks in the ${OBS_WINDOW}s window — it was not forging for some reason OTHER than KES expiry (wedged, not caught up, or not a block producer). The zero-forge predicate below is vacuous; investigate dugite-bp.log before trusting this step (#1055/#1057)"
else
    ok "dugite-bp ran $DBP_CHECKS leadership check(s) in the window — it was live and attempting to forge, so the zero-forge predicate is meaningful"
fi

if [ "$DBP_DELTA" -eq 0 ]; then
    if [ "$DBP_CHECKS" -gt 0 ]; then
        ok "dugite-bp forged 0 new blocks in the ${OBS_WINDOW}s post-expiry window (while actively running $DBP_CHECKS leadership checks)"
    else
        note "dugite-bp forged 0 new blocks — NOT counted as a pass, see the INCONCLUSIVE above"
    fi
else
    bad "dugite-bp forged $DBP_DELTA block(s) after its KES key should have expired at slot $KES_DEATH_SLOT"
fi
if [ "$CBP_DELTA" -gt 0 ]; then
    ok "cardano-bp (refreshed KES) kept forging ($CBP_DELTA blocks) in the same window"
else
    bad "cardano-bp forged 0 blocks in the same window — cannot distinguish KES-expiry from a stalled devnet"
fi

# Pinned diagnostic. After the #1054 fix, the per-slot upper-bound gate in
# try_forge_block_at fires BEFORE the VRF leader check and skips forging once
# expired (matching Haskell's HotKey poison-once-then-short-circuit), logging
# `TraceNodeCannotForge: KES key expired` at WARN. That gate short-circuits
# before forge_block is ever called, so the OLDER
# `TraceForgeStateUpdateError: block forging failed: KES key expired` wrapper
# (forge.rs bail -> node/mod.rs Err(e), only reachable when dugite-bp was
# VRF-elected leader at/after expiry) no longer fires. Match EITHER form so
# the assertion holds both before and after the fix: the anchored phrase
# `KES key expired` appears in both.
KES_EXPIRED_PATTERN='KES key expired'
if expect_log_errors "$LD_LOGS/dugite-bp.log" "$MARK_DBP" "$KES_EXPIRED_PATTERN"; then
    ok "dugite-bp.log carries the KES-expiry diagnostic"
else
    bad "dugite-bp.log missing the KES-expiry diagnostic after line $MARK_DBP (dugite-bp may not have been VRF-elected leader in this window — see header risk note; consider a longer KES_OBS_WINDOW)"
fi
if assert_no_other_errors "$LD_LOGS/dugite-bp.log" "$MARK_DBP" "$ALLOWLIST"; then
    ok "no unexpected error-class lines in dugite-bp.log"
else
    bad "unexpected error-class line(s) in dugite-bp.log — see above"
fi
step_row "2-dugite-kes-expiry" "$F0"

# ============================================================ STEP 3 =========
F0=$FAILURES
step "3. future-period opcert (current+5) — PraosCannotForgeKeyNotUsableYet"
CUR_P3=$(cur_period)
FUTURE_P3=$((CUR_P3 + 5))
note "current kes period=$CUR_P3 (slot $(cur_slot)); issuing opcert at period=$FUTURE_P3"
cp "$LD_KEYS/pool1/opcert.counter" "$WORK/p1.counter.step3"
if issue_pool1_opcert "$FUTURE_P3" "$WORK/p1.counter.step3" \
        "$WORK/p1-future.kes.skey" "$WORK/p1-future.kes.vkey" "$WORK/p1-future.opcert.cert"; then
    ok "issued a future-period opcert (real counter file untouched — see header)"
    MARK_DBP=$(log_mark "$LD_LOGS/dugite-bp.log")
    restart_dugite_bp_with_creds "$WORK/p1-future.kes.skey" "$WORK/p1-future.opcert.cert"
    if [ -S "$LD_DUGITE_BP_SOCK" ]; then
        ok "dugite-bp restarted with the future-period opcert"
        DBP_BEFORE=$(dbp_forge_count)
        sleep "$OBS_WINDOW"
        DBP_AFTER=$(dbp_forge_count)
        DBP_DELTA=$((DBP_AFTER - DBP_BEFORE))
        if [ "$DBP_DELTA" -eq 0 ]; then
            ok "dugite-bp forged 0 blocks in ${OBS_WINDOW}s with a not-yet-valid opcert"
        else
            bad "dugite-bp forged $DBP_DELTA block(s) despite the opcert not being valid until period $FUTURE_P3"
        fi
        # Pinned diagnostics: the per-slot gate in
        # crates/dugite-node/src/node/mod.rs "Step 5b" (~line 9824,
        # `checkShouldForge` == CannotForge per Haskell's
        # `praosCheckCanForge`) logs TraceNodeCannotForge every slot the
        # wall-clock KES period precedes the opcert's start period; the
        # one-time startup check (~line 2345) logs the WARN form once at
        # boot if tip_slot > 0.
        FUTURE_PATTERN='TraceNodeCannotForge: PraosCannotForgeKeyNotUsableYet|Operational certificate KES period is in the future'
        if expect_log_errors "$LD_LOGS/dugite-bp.log" "$MARK_DBP" "$FUTURE_PATTERN"; then
            ok "dugite-bp.log carries the future-period diagnostic"
        else
            bad "dugite-bp.log missing the future-period diagnostic after line $MARK_DBP"
        fi
        if assert_no_other_errors "$LD_LOGS/dugite-bp.log" "$MARK_DBP" "$ALLOWLIST"; then
            ok "no unexpected error-class lines in dugite-bp.log across the restart"
        else
            bad "unexpected error-class line(s) in dugite-bp.log across the restart — see above"
        fi
    else
        bad "dugite-bp socket not up after the future-period restart"
    fi
else
    bad "could not issue the future-period opcert: $(tail -3 "$WORK/opcert.err" 2>/dev/null | tr '\n' ' ')"
fi
step_row "3-future-period-opcert" "$F0"

# ============================================================ STEP 4 =========
F0=$FAILURES
step "4. counter over-increment (+2 from last-used) — dugite forging must be REJECTED by Haskell"
CUR_P4=$(cur_period)
cp "$LD_KEYS/pool1/opcert.counter" "$WORK/p1.counter.step4"
if issue_pool1_opcert "$CUR_P4" "$WORK/p1.counter.step4" \
        "$WORK/p1-skip.kes.skey" "$WORK/p1-skip.kes.vkey" "$WORK/p1-skip.opcert.cert" \
   && issue_pool1_opcert "$CUR_P4" "$WORK/p1.counter.step4" \
        "$WORK/p1-over.kes.skey" "$WORK/p1-over.kes.vkey" "$WORK/p1-over.opcert.cert"; then
    ok "issued an over-incremented opcert (counter = last-chain-used + 2) at current period $CUR_P4"
    MARK_DBP=$(log_mark "$LD_LOGS/dugite-bp.log")
    MARK_ARB=$(log_mark "$LD_LOGS/cardano-arbiter.log")
    MARK_CBP=$(log_mark "$LD_LOGS/cardano-bp.log")
    restart_dugite_bp_with_creds "$WORK/p1-over.kes.skey" "$WORK/p1-over.opcert.cert"
    if [ -S "$LD_DUGITE_BP_SOCK" ]; then
        ok "dugite-bp restarted with the over-incremented opcert"
        ADOPTED=0
        ADOPTED_HASH=""
        FORGED_HASHES=""
        for _ in $(seq 1 30); do
            sleep 5
            FORGED_HASHES=$(forged_hashes_since "$MARK_DBP")
            [ -z "$FORGED_HASHES" ] && continue
            AH=$(tip_field "$LD_CARDANO_ARBITER_SOCK" .hash)
            for h in $FORGED_HASHES; do
                if [ "$AH" = "$h" ]; then ADOPTED=1; ADOPTED_HASH="$h"; break 2; fi
            done
        done
        if [ -z "$FORGED_HASHES" ]; then
            ok "dugite-bp did not forge with the over-incremented opcert (detail=did-not-forge — conservative; the receiving-side reject was never exercised this run)"
            note "did-not-forge is weaker evidence than forged-and-rejected; a longer KES_OBS_WINDOW or a re-run raises the odds of a VRF-elected slot"
        else
            note "dugite-bp forged $(printf '%s\n' "$FORGED_HASHES" | wc -l | tr -d '[:space:]') block(s) with the over-incremented opcert: $(printf '%s ' $FORGED_HASHES)"
            if [ "$ADOPTED" -eq 1 ]; then
                bad "WEDGE: the arbiter ADOPTED dugite-forged block $ADOPTED_HASH with an over-incremented opcert counter — dugite accepted its own header that a Haskell peer would reject"
            else
                ok "forged-and-rejected: the arbiter never adopted any of dugite-bp's over-incremented-counter blocks"
            fi
            INVALID_ARB=$(count_matching_since "$LOG_ERROR_PATTERN" "$LD_LOGS/cardano-arbiter.log" "$MARK_ARB")
            INVALID_CBP=$(count_matching_since "$LOG_ERROR_PATTERN" "$LD_LOGS/cardano-bp.log" "$MARK_CBP")
            note "invalid-block-class lines since mark (new-tracer + legacy namespaces): arbiter=$INVALID_ARB cardano-bp=$INVALID_CBP"
            COUNTER_HINT=$(count_matching_since '[Cc]ounter' "$LD_LOGS/cardano-arbiter.log" "$MARK_ARB")
            note "arbiter log lines mentioning 'counter' since mark: $COUNTER_HINT (best-effort detail only — not required for the verdict above)"
        fi
    else
        bad "dugite-bp socket not up after the over-incremented-counter restart"
    fi
else
    bad "could not issue the over-incremented opcert: $(tail -3 "$WORK/opcert.err" 2>/dev/null | tr '\n' ' ')"
fi
step_row "4-counter-over-increment" "$F0"

# ============================================================ STEP 5 =========
F0=$FAILURES
step "5. valid rotation (+1 from last-used) — forging resumes, arbiter adopts"
CUR_P5=$(cur_period)
if issue_pool1_opcert "$CUR_P5" "$LD_KEYS/pool1/opcert.counter" \
        "$WORK/p1-final.kes.skey" "$WORK/p1-final.kes.vkey" "$WORK/p1-final.opcert.cert"; then
    ok "issued a valid +1 opcert (counter = last-chain-used + 1) at current period $CUR_P5 — the ONLY issuance in this round against the real counter file"
    MARK_DBP=$(log_mark "$LD_LOGS/dugite-bp.log")
    restart_dugite_bp_with_creds "$WORK/p1-final.kes.skey" "$WORK/p1-final.opcert.cert"
    if [ -S "$LD_DUGITE_BP_SOCK" ]; then
        ok "dugite-bp restarted with the valid rotation opcert"
        ADOPTED=0
        ADOPTED_HASH=""
        for _ in $(seq 1 36); do
            sleep 5
            NEW_HASHES=$(forged_hashes_since "$MARK_DBP")
            [ -z "$NEW_HASHES" ] && continue
            AH=$(tip_field "$LD_CARDANO_ARBITER_SOCK" .hash)
            for h in $NEW_HASHES; do
                if [ "$AH" = "$h" ]; then ADOPTED=1; ADOPTED_HASH="$h"; break 2; fi
            done
        done
        if [ "$ADOPTED" -eq 1 ]; then
            ok "forging resumed and the arbiter adopted dugite-bp block $ADOPTED_HASH within 180s"
            # RED-PROOF: this is the SAME "did the arbiter adopt hash X"
            # detector step 4 uses in the negative direction. A positive hit
            # here proves the detector can return true at all — if it could
            # never fire (wrong jq field, wrong socket, hash-format mismatch),
            # step 4's "arbiter did NOT adopt" verdict would be vacuously true
            # rather than a real observation.
            ok "RED-PROOF: the adopted-hash detector fired here — proves step 4's 'arbiter did NOT adopt' check is a real negative, not a detector that can never fire"
        else
            bad "forging did not resume / arbiter did not adopt a dugite-bp block within 180s of the valid rotation"
        fi
    else
        bad "dugite-bp socket not up after the valid-rotation restart"
    fi
else
    bad "could not issue the valid rotation opcert: $(tail -3 "$WORK/opcert.err" 2>/dev/null | tr '\n' ' ')"
fi

note "kes-period-info parity across both sockets (cardano-cli against both, per the 09-cli-parity convention — this measures the NODE, not the CLI)"
# `query kes-period-info` prints a HUMAN-READABLE report to stdout; JSON is
# only emitted via --out-file. Piping stdout to jq yielded empty on BOTH
# sockets (including the unmodified Haskell arbiter) — a harness bug, not a
# dugite gap. Write to a file and read that.
KPI_FILTER='del(.qKesRemainingSlotsInKesPeriod)'
_kpi() { # _kpi <socket>
    local out; out="$WORK/kpi-$(basename "$1").json"
    cardano-cli conway query kes-period-info --testnet-magic "$LD_MAGIC" \
        --socket-path "$1" --op-cert-file "$LD_KEYS/pool1/opcert.cert" \
        --out-file "$out" >/dev/null 2>&1
    [ -s "$out" ] && jq -S "$KPI_FILTER" "$out" 2>/dev/null
}
KPI_DBP=$(_kpi "$LD_RELAY_SOCK")
KPI_ARB=$(_kpi "$LD_CARDANO_ARBITER_SOCK")
if [ -n "$KPI_DBP" ] && [ -n "$KPI_ARB" ] && [ "$KPI_DBP" = "$KPI_ARB" ]; then
    ok "kes-period-info parity: dugite (via relay) matches the Haskell arbiter"
elif [ -z "$KPI_DBP" ] || [ -z "$KPI_ARB" ]; then
    bad "kes-period-info could not be read from both sockets (dugite-empty=$([ -z "$KPI_DBP" ] && echo yes || echo no) arbiter-empty=$([ -z "$KPI_ARB" ] && echo yes || echo no))"
else
    bad "kes-period-info DIVERGENCE: dugite=$KPI_DBP vs arbiter=$KPI_ARB"
fi
step_row "5-valid-rotation" "$F0"

# ============================================================ SUMMARY ========
step "SUMMARY"
if [ "$FAILURES" -eq 0 ]; then
    ok "kes round: all assertions passed"
else
    bad "kes round: $FAILURES assertion(s) failed"
fi
note "evidence: $CSV"

step "TEARDOWN (terminal round — dugite-bp's keys were rotated through 5 opcerts; this devnet is not reusable)"
./stop.sh >/dev/null 2>&1
note "devnet stopped"

exit "$FAILURES"
