//! Upstream `plutus-tx`-compiled scripts as an independent oracle (#969/#970).
//!
//! # What these bytes are, and why they are not Aiken's
//!
//! `tests/conformance/upstream/plutus-examples.json` is vendored, unmodified,
//! from `Test.Cardano.Ledger.Plutus.Examples` in IntersectMBO/cardano-ledger.
//! That module is generated by `plutus-preprocessor` from `plutus-tx` source
//! using `plutus-tx-plugin`, and its output is checked into cardano-ledger. So
//! these programs encode **upstream's** view of Plutus Core and of the
//! ScriptContext, which is the only view conformance is measured against.
//!
//! This matters because the alternative is circular. Aiken is a third-party
//! compiler; if its stdlib's representation and dugite's construction share a
//! misunderstanding, an Aiken-built validator agrees with the bug and passes.
//! #772 established that already — "aiken parity is circular" — and the
//! decisive method there was an independent cardano-ledger dump, not Aiken.
//!
//! # What is actually being asserted
//!
//! Each entry carries the script bytes AND the `ScriptHash` cardano-ledger
//! recorded beside them. That hash is the oracle: it is computed by upstream,
//! over these exact bytes, with upstream's language-tag discipline. dugite
//! reproducing it proves the tag byte, the hash domain and the treatment of the
//! CBOR-wrapped program all agree — none of which is inferable from the bytes
//! alone.
//!
//! The decode assertion is the second half. These are real `plutus-tx` outputs
//! with `plutus-tx`'s prelude and calling convention, structurally unlike the
//! hand-written and Aiken-built programs `dugite-uplc` was mostly exercised
//! against. #656 (`De Bruijn index 2 out of range`) was found by exactly this
//! kind of shape difference.
//!
//! # What is NOT asserted here
//!
//! Nothing is *evaluated*. Running `purposeIsWellformedNoDatum` requires a real
//! ScriptContext, which is a devnet concern, not a unit-test one — see the
//! `17-context-inspecting` tx-zoo category. This file pins the artifacts so the
//! devnet has something authoritative to run.

use std::path::PathBuf;

use dugite_uplc::Program;

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/conformance/upstream/plutus-examples.json")
}

struct Entry {
    name: String,
    lang: String,
    bytes: Vec<u8>,
    upstream_hash: String,
}

fn load() -> (String, Vec<Entry>) {
    let raw = std::fs::read_to_string(fixture_path()).expect(
        "tests/conformance/upstream/plutus-examples.json is missing — regenerate with \
         scripts/regenerate-conformance-corpus/extract-plutus-examples.py",
    );
    let doc: serde_json::Value = serde_json::from_str(&raw).expect("fixture is not valid JSON");
    let source_ref = doc["source_ref"].as_str().expect("source_ref").to_string();

    let mut out = Vec::new();
    for script in doc["scripts"].as_array().expect("scripts array") {
        let name = script["name"].as_str().expect("name").to_string();
        let langs = script["languages"].as_object().expect("languages object");
        for (lang, v) in langs {
            let hex = v["script_hex"].as_str().expect("script_hex");
            out.push(Entry {
                name: name.clone(),
                lang: lang.clone(),
                bytes: hex_to_bytes(hex),
                upstream_hash: v["script_hash"].as_str().expect("script_hash").to_string(),
            });
        }
    }
    (source_ref, out)
}

fn hex_to_bytes(s: &str) -> Vec<u8> {
    assert!(s.len().is_multiple_of(2), "odd-length hex");
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("hex digit"))
        .collect()
}

fn to_hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

/// The fixture must not silently shrink.
///
/// A regenerator whose parser stops matching after an upstream reformat would
/// otherwise cut coverage without failing anything — the "reports success while
/// measuring nothing" family this repo keeps finding (#916/#945/#953/#987).
#[test]
fn fixture_covers_every_upstream_script_and_language() {
    let (source_ref, entries) = load();
    assert!(
        !source_ref.is_empty(),
        "the fixture must record which cardano-ledger ref it came from"
    );

    let mut names: Vec<&str> = entries.iter().map(|e| e.name.as_str()).collect();
    names.sort_unstable();
    names.dedup();
    assert_eq!(
        names.len(),
        14,
        "upstream defines 14 example scripts, fixture has {}: {names:?}",
        names.len()
    );

    // Every script exists for V2/V3/V4. V1 is absent for exactly one:
    // `inputsOverlapsWithRefInputs`, because V1 has no reference inputs.
    for lang in ["V2", "V3", "V4"] {
        let n = entries.iter().filter(|e| e.lang == lang).count();
        assert_eq!(n, 14, "expected 14 {lang} scripts, got {n}");
    }
    let v1 = entries.iter().filter(|e| e.lang == "V1").count();
    assert_eq!(
        v1, 13,
        "expected 13 V1 scripts (no ref inputs in V1), got {v1}"
    );

    // The context-inspecting ones are the point of the exercise; assert they
    // are present by name so a future regeneration cannot drop them quietly.
    for required in [
        "purposeIsWellformedNoDatum",
        "purposeIsWellformedWithDatum",
        "datumIsWellformed",
        "inputsOutputsAreNotEmptyNoDatum",
        "inputsOverlapsWithRefInputs",
        "redeemerSameAsDatum",
    ] {
        assert!(
            names.contains(&required),
            "{required} is a CONTEXT-INSPECTING script — losing it reduces this \
             fixture to the always-true validators it was written to replace"
        );
    }
}

/// dugite must reproduce cardano-ledger's own `ScriptHash` for every script.
///
/// `script_ref_hash` is the production helper — the same one the ledger uses to
/// match a supplied script against a script address — not a test-local
/// reimplementation. That is deliberate: hashing the bytes here with a
/// hand-rolled `blake2b_224(tag || bytes)` would assert only that this file and
/// upstream agree, while leaving dugite's real path untested.
#[test]
fn dugite_reproduces_upstream_script_hashes() {
    use dugite_primitives::transaction::ScriptRef;

    let (source_ref, entries) = load();
    let mut mismatches = Vec::new();

    for e in &entries {
        let script_ref = match e.lang.as_str() {
            "V1" => ScriptRef::PlutusV1(e.bytes.clone()),
            "V2" => ScriptRef::PlutusV2(e.bytes.clone()),
            "V3" => ScriptRef::PlutusV3(e.bytes.clone()),
            "V4" => ScriptRef::PlutusV4(e.bytes.clone()),
            other => panic!("unknown language {other}"),
        };
        let got = to_hex(&dugite_uplc::tx_info_populate::script_ref_hash(&script_ref));
        if got != e.upstream_hash {
            mismatches.push(format!(
                "  {}/{}: dugite={} upstream={}",
                e.name, e.lang, got, e.upstream_hash
            ));
        }
    }

    assert!(
        mismatches.is_empty(),
        "script hash divergence from cardano-ledger {source_ref} \
         ({} of {} scripts):\n{}",
        mismatches.len(),
        entries.len(),
        mismatches.join("\n")
    );
}

/// Every upstream script must decode through `dugite-uplc`'s real decoder.
///
/// The bytes are `serialiseCompiledCode` output — flat, wrapped in a single
/// CBOR byte string — which is what goes on chain, so `Program::from_cbor` is
/// the correct entry point rather than `from_flat`.
#[test]
fn every_upstream_script_decodes() {
    let (source_ref, entries) = load();
    let mut failures = Vec::new();

    for e in &entries {
        match Program::from_cbor(&e.bytes) {
            Ok(p) => {
                let (maj, min, patch) = &p.version;
                // plutus-tx emits 1.0.0 for V1/V2 and 1.1.0 for V3+. Anything
                // else means we mis-decoded the header, not that upstream
                // changed compilers.
                let one = num_bigint::BigUint::from(1u32);
                let zero = num_bigint::BigUint::from(0u32);
                assert!(
                    *maj == one && *min <= one && *patch == zero,
                    "{}/{}: implausible version {maj}.{min}.{patch} — the header \
                     was mis-decoded",
                    e.name,
                    e.lang
                );
            }
            Err(err) => failures.push(format!("  {}/{}: {err}", e.name, e.lang)),
        }
    }

    assert!(
        failures.is_empty(),
        "{} of {} upstream plutus-tx programs failed to decode (cardano-ledger \
         {source_ref}):\n{}",
        failures.len(),
        entries.len(),
        failures.join("\n")
    );
}
